# Generated by Django 4.1.3 on 2023-03-30 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
