# Generated by Django 4.1.3 on 2023-04-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_subscribe_subscribed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
